const { default: mongoose } = require("mongoose");
let tripSchema=mongoose.Schema({
    pickUpTime:{
        type:String,
        default:""
    },
    isOtherTrip:{
        type:Boolean,
        default:false
    },
    mileage:{
     type:String,
     default:0
    },
    isComplted:{
        type:Boolean,
        default:false
    },
    legId:{
        type:String,
        default:""
    },
    confirmation:{
        type:String,
        default:""
    },
    addedBy:{
        type:String,
        default:""
    },
    reviews:{
        type:Array,
        default:[]
    },
    pickUpDate:{
        type:String,
      default:""
    },
    driverName:{
        type:String,
        default:""
    },
    patientName:{
        type:String,
        default:""
    },
    patientType:{
        type:String,
        default:""
    },
    patientRef:{
        type:String,
        default:""
    },
    patientPhoneNumber:{
        type:String
    },
    driverRef:{
        type:String,
        default:""
    },
    appointmentTime:{
        type:String
    },
    status:{
        type:String,
        default:"Not Assigned"
    },
    pauses:[ {
            pauseTime: { type: Date, required: true },
            resumeTime: { type: Date },
        }],
    pickUpAddress:{
        type:String,
        default:""
    },
    dropOffAddress:{
        type:String,
        default:""
    },
    startedAt:{
        type:Date,
        default:Date.now
    },
    endedAt:{
        type:Date
    },
    timeTaken:{
        type:Number,
        default:0
    },
    completedAt:{
        type:Date
    },
    possibleRoutes:{
        type:Array,
        default:[]
    },
    patientPhotoUrl:{
        type:String,
        default:""
    },
    patientSignatureUrl:{
        type:String,
        default:""
    },
    driverSignatureUrl:{
        type:String,
        default:""
    },
    noOfPassengers:{
        type:Number,
        default:1
    },
    notes:{
        type:String,
        default:""
    },
    tripType:{
        type:String,
        default:""
    },
    tripGroupId:{
        type:mongoose.Schema.Types.ObjectId,
        default:null
    },
    addedByCompanyCode:{
        type:String,
        default:""
    },
    createdAt: { type: Date, default: Date.now }
})
let TripModel=mongoose.model("Trips",tripSchema)
module.exports=TripModel

